{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red38\green38\blue38;\red236\green236\blue236;\red16\green121\blue2;
\red117\green117\blue117;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
security:\
  basic:\
    enabled: \cf4 \expnd0\expndtw0\kerning0
false\cf2 \expnd0\expndtw0\kerning0
 \cf5 \expnd0\expndtw0\kerning0
# turn of securing our application endpoints\cf2 \expnd0\expndtw0\kerning0
\
\
management:\
  security:\
    enabled: \cf4 \expnd0\expndtw0\kerning0
false\cf2 \expnd0\expndtw0\kerning0
 \cf5 \expnd0\expndtw0\kerning0
# turn of securing the actuator endpoints}